import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import './globals.css';
import Components from '@/components';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};
//https://demo.templatemonster.com/demo/183965.html?_gl=1*1j7clu2*_ga*MTcwNzg5MzczMC4xNzExMjc0NjYy*_ga_FTPYEGT5LY*MTcxMTI3NDY2Mi4xLjEuMTcxMTI3NDY2Mi42MC4wLjA.

export default function RootLayout({
    children,
}: Readonly<{children: React.ReactNode}>) {
    return (
        <html lang='en'>
            <body className={inter.className + 'max-w-full overflow-x-hidden'}>
                <Components>{children}</Components>
            </body>
        </html>
    );
}
